### ISSUE TITLE
FR: Use `qs` package for serialization

### ISSUE THREAD

**Issue by saadaslam** [sparklyr/sparklyr#2981]
Branching off of issue #2959 I am requesting to see if it is possible to add an option to use `qs` to serialize objects in `spark_apply`. This, I expect will greatly speed up the start-up time when large environments are involved with `spark_apply`, particularly when you're using `registerDoSpark` as a back-end for tidymodels.

Thanks!

**Comment by saadaslam** [comment]
Thanks! I'll check it out shortly.

**Comment by yitao-li** [comment]
@saadaslam FYI another possible improvement that is orthogonal to custom serialization for `spark_apply` is the proposal in https://github.com/sparklyr/sparklyr/issues/1945

Long story short, currently the way `doSpark()` works causes a Spark worker node to receive a serialized copy to some R environment each time it receives a partition to be processed. In this case a feature called "broadcast variable" in Spark (https://spark.apache.org/docs/2.2.0/rdd-programming-guide.html#broadcast-variables) can be used to avoid copying the same serialized R object to each worker multiple times.

**Comment by saadaslam** [comment]
@yitao-li i think the improvement with using the `qs` serializer and `registerDoSpark` is actually within `spark_apply`. after doing some debugging, it seems like the iterator items are being serialized with `qs` but the environment that contains the large folds object (from my example above in #2959) is still being serialized with base R (line 259 of `spark_apply.R`: `closure <- if (is.function(f)) suppressWarnings(serialize(f, NULL, version = serialize_version)) else f`). the reduction in size is pretty meaningful between the two approaches to the point where my example in #2959 may actually end up working because the resulting length of the raw vector is less than the integer maximum. 
``` r
library(foreach)
library(tidymodels)
library(modeldata)
library(sparklyr)

options(
  warn = 2
)

sc <- spark_connect("local")

data(credit_data)

mars_mod <- mars(num_terms = tune(), prod_degree = tune()) %>%
  set_mode("classification") %>%
  set_engine("earth")

wflow <- workflow() %>%
  add_model(mars_mod) %>%
  add_formula(Status ~ .)

wflow_parms <- parameters(wflow) %>%
  update(num_terms = num_terms(c(5, 10)))

metrics <- metric_set(roc_auc, mn_log_loss)

set.seed(22)

grid_for_tuning <- grid_max_entropy(wflow_parms, size = 10)
folds <- credit_data %>%
  tidyr::drop_na() %>%
  slice_sample(n = 1e7, replace = TRUE) %>%
  vfold_cv(strata = "Status")

ser <- serialize(folds, NULL)
qser <- qs::qserialize(folds)

lobstr::obj_size(folds) ## 920,014,704 B
lobstr::obj_size(ser) ## 5,960,012,400 B
lobstr::obj_size(qser) ## 872,569,696 B

scales::comma(length(ser)) ## 5,960,012,345
scales::comma(length(qser)) ## 872,569,642
```

**Comment by yitao-li** [comment]
@saadaslam Great. Thanks for the feedback.

https://github.com/sparklyr/sparklyr/pull/3005 contains the change for applying custom serialization protocols within `spark_apply()`.

With that change, the relevant configuration will be `options(sparklyr.spark_apply.serializer = "qs")` or

```
options(sparklyr.spark_apply.serializer = function(x) qs::qserialize(x, preset = "fast"))
options(sparklyr.spark_apply.deserializer = function(x) qs::qdeserialize(x))
```

**Comment by saadaslam** [comment]
So, I seem to be getting a couple issues w/ my reprex above. See below for when I set `options(sparklyr.spark_apply.serializer = "qs")`:

``` r
library(sparklyr)
#> 
#> Attaching package: 'sparklyr'
#> The following object is masked from 'package:stats':
#> 
#>     filter

packageVersion("sparklyr")
#> [1] '1.6.2'

library(foreach)
library(tidymodels)
#> ── Attaching packages ────────────────────────────────────── tidymodels 0.1.2 ──
#> ✓ broom     0.7.2      ✓ recipes   0.1.15
#> ✓ dials     0.0.9      ✓ rsample   0.0.8 
#> ✓ dplyr     1.0.2      ✓ tibble    3.0.4 
#> ✓ ggplot2   3.3.2      ✓ tidyr     1.1.2 
#> ✓ infer     0.5.3      ✓ tune      0.1.2 
#> ✓ modeldata 0.1.0      ✓ workflows 0.2.1 
#> ✓ parsnip   0.1.4      ✓ yardstick 0.0.7 
#> ✓ purrr     0.3.4
#> ── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──
#> x purrr::accumulate() masks foreach::accumulate()
#> x purrr::discard()    masks scales::discard()
#> x dplyr::filter()     masks sparklyr::filter(), stats::filter()
#> x purrr::invoke()     masks sparklyr::invoke()
#> x dplyr::lag()        masks stats::lag()
#> x recipes::step()     masks stats::step()
#> x purrr::when()       masks foreach::when()
library(modeldata)

options(
  warn = 2,
  sparklyr.connect.enablehivesupport = FALSE,
  sparklyr.spark_apply.serializer = "qs"
  # sparklyr.spark_apply.serializer = function(x) qs::qserialize(x, preset = "fast"),
  # sparklyr.spark_apply.deserializer = function(x) qs::qdeserialize(x)
)

sc <- spark_connect(master = "local")

data(credit_data)

mars_mod <- mars(num_terms = tune(), prod_degree = tune()) %>%
  set_mode("classification") %>%
  set_engine("earth")

wflow <- workflow() %>%
  add_model(mars_mod) %>%
  add_formula(Status ~ .)

wflow_parms <- parameters(wflow) %>%
  update(num_terms = num_terms(c(5, ncol(credit_data))))

metrics <- metric_set(roc_auc, mn_log_loss)

set.seed(22)

grid_for_tuning <- grid_max_entropy(wflow_parms, size = 10)
folds <- credit_data %>%
  tidyr::drop_na() %>%
  #  slice_sample(n = 1e7, replace = TRUE) %>%
  vfold_cv(strata = "Status")

registerDoSpark(sc)

tune_grid(
  wflow,
  resamples = folds,
  grid = grid_for_tuning,
  metrics = metrics,
  param_info = wflow_parms
  # control = control_grid(
  #   parallel_over = "everything"
  # )
) -> tuned
#> Error in c_qserialize(x, preset, algorithm, compress_level, shuffle_control, : bad binding access
```

<sup>Created on 2021-04-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by saadaslam** [comment]
Here's the reprex for when I specify a function for `sparklyr.spark_apply.serializer`:

``` r
library(sparklyr)
#> 
#> Attaching package: 'sparklyr'
#> The following object is masked from 'package:stats':
#> 
#>     filter

packageVersion("sparklyr")
#> [1] '1.6.2'

library(foreach)
library(tidymodels)
#> ── Attaching packages ────────────────────────────────────── tidymodels 0.1.2 ──
#> ✓ broom     0.7.2      ✓ recipes   0.1.15
#> ✓ dials     0.0.9      ✓ rsample   0.0.8 
#> ✓ dplyr     1.0.2      ✓ tibble    3.0.4 
#> ✓ ggplot2   3.3.2      ✓ tidyr     1.1.2 
#> ✓ infer     0.5.3      ✓ tune      0.1.2 
#> ✓ modeldata 0.1.0      ✓ workflows 0.2.1 
#> ✓ parsnip   0.1.4      ✓ yardstick 0.0.7 
#> ✓ purrr     0.3.4
#> ── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──
#> x purrr::accumulate() masks foreach::accumulate()
#> x purrr::discard()    masks scales::discard()
#> x dplyr::filter()     masks sparklyr::filter(), stats::filter()
#> x purrr::invoke()     masks sparklyr::invoke()
#> x dplyr::lag()        masks stats::lag()
#> x recipes::step()     masks stats::step()
#> x purrr::when()       masks foreach::when()
library(modeldata)

options(
  warn = 2,
  sparklyr.connect.enablehivesupport = FALSE,
  # sparklyr.spark_apply.serializer = "qs"
  sparklyr.spark_apply.serializer = function(x) qs::qserialize(x, preset = "fast"),
  sparklyr.spark_apply.deserializer = function(x) qs::qdeserialize(x)
)

sc <- spark_connect(master = "local")

data(credit_data)

mars_mod <- mars(num_terms = tune(), prod_degree = tune()) %>%
  set_mode("classification") %>%
  set_engine("earth")

wflow <- workflow() %>%
  add_model(mars_mod) %>%
  add_formula(Status ~ .)

wflow_parms <- parameters(wflow) %>%
  update(num_terms = num_terms(c(5, ncol(credit_data))))

metrics <- metric_set(roc_auc, mn_log_loss)

set.seed(22)

grid_for_tuning <- grid_max_entropy(wflow_parms, size = 10)
folds <- credit_data %>%
  tidyr::drop_na() %>%
  #  slice_sample(n = 1e7, replace = TRUE) %>%
  vfold_cv(strata = "Status")

registerDoSpark(sc)

tune_grid(
  wflow,
  resamples = folds,
  grid = grid_for_tuning,
  metrics = metrics,
  param_info = wflow_parms
  # control = control_grid(
  #   parallel_over = "everything"
  # )
) -> tuned
#> Error in serialize_impl(f, version = serialize_version): unused argument (version = serialize_version)
```

<sup>Created on 2021-04-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by yitao-li** [comment]
@saadaslam I think https://github.com/sparklyr/sparklyr/pull/3022 should fix it. I was able to run both versions of your example code successfully with that change. I was using `qs` version 0.24.1 though (which is different from the one you had in your R env), but I don't think `qs` version should matter here.

**Comment by saadaslam** [comment]
@yitao-li  weird, I still get the `Error in c_qserialize(x, preset, algorithm, compress_level, shuffle_control, : bad binding access` error when I load with `library(sparklyr)`. When loading with `devtools::load_all(".")` the reprex works just fine.

**Comment by saadaslam** [comment]
And to add -- the error goes away with `qs` version 0.24.1.
