### ISSUE TITLE
ml_save() and ml_load() not working in Databricks: [PATH_NOT_FOUND] Path does not exist dbfs:/path/model/metadata/part-00000.

### ISSUE THREAD

**Issue by henryryan17** [sparklyr/sparklyr#3478]
I have been trying to use ml_save() and ml_load() in Databricks (cluster-save/cluster-load), but continually get this error:

[PATH_NOT_FOUND] Path does not exist dbfs:/path/model/metadata/part-00000.

Here is some code that recreates the issue:

```
suppressMessages(library(sparklyr)) 
suppressMessages(library(dplyr)) 
suppressMessages(library(arrow)) 

sc <- spark_connect(method = "databricks")

iris_tbl <- sdf_copy_to(sc, iris, name = "iris_tbl", overwrite = TRUE)

model <- iris_tbl %>%
  ml_linear_regression(Sepal_Length ~ Sepal_Width + Petal_Length + Petal_Width)


ml_save(model, path = "dbfs:/path/model")

loaded_model <- ml_load(sc, path = "dbfs:/path/model")
```

> Error: org.apache.spark.sql.AnalysisException: [PATH_NOT_FOUND] Path does not
> exist: dbfs:/path/model/metadata/part-00000. SQLSTATE: 42K03

Looking at the dbfs:/path/model/metadata/ directory, I see this:
```
_SUCCESS
_committed_6424082946698911525
_started_6424082946698911525
part-00000-tid-6424082946698911525-1effc116-480f-4584-9255-768eb599e04d-63-1-c000.txt
```

It seems like the ml_load() function is hardcoded to look specifically for "/metadata/part-00000", although perhaps I am grossly misunderstanding that function (screen shot take from the main branch of this repo):

![Image](https://github.com/user-attachments/assets/2b2ed7f8-5997-468d-bf36-a6c4ad05efb6)

I have looked at this: https://github.com/sparklyr/sparklyr/issues/1088

Folks seemed to have some similar issues, but it sounds like this was resolved and cluster-save/cluster-load should be feasible. Am I missing something here?

**Comment by edgararuiz** [comment]
Hi! Can you make sure you're running the latest version of `sparklyr`?  I fixed that in the 1.9.0 release: https://github.com/sparklyr/sparklyr/commit/bf80bb9991b617c1445d57f674a226f9c9d2df1a

**Comment by henryryan17** [comment]
@edgararuiz - Thanks for getting back to me. Despite using the latest version of sparklyr (1.9.0) I am still getting an error. The error is slightly different this time:

![Image](https://github.com/user-attachments/assets/b4337d60-c306-4ca6-b387-d9fdde339684)

Looking at the dbfs:/path/model/metadata/ directory, I see this:
`_SUCCESS`
`_committed_6299138540998062560`
`_started_6299138540998062560`
`part-00000-tid-6299138540998062560-ea7d1d08-e660-4c71-831e-97a6c5222068-119-1-c000.txt`

**The same code reproduces the issue.**

Just for confirmation, here is a screen shot of my sparklyr version:

![Image](https://github.com/user-attachments/assets/52b12398-4314-42aa-8451-ab524ac20db1)

```
%r
install.packages("sparklyr")
library(sparklyr)

library(dplyr)
library(arrow)

packageVersion("sparklyr")
## 1.9.0

sc <- spark_connect(method = "databricks")

iris_tbl <- sdf_copy_to(sc, iris, name = "iris_tbl", overwrite = TRUE)

model <- iris_tbl %>%
  ml_linear_regression(Sepal_Length ~ Sepal_Width + Petal_Length + Petal_Width)

ml_save(model, path = "dbfs:/path/model", overwrite = TRUE)

loaded_model <- ml_load(sc, path = "dbfs:/path/model")
```

**Comment by henryryan17** [comment]
@edgararuiz - hm interesting. Running `list.files("dbfs:/path/model/metadata/")` returns this:

![Image](https://github.com/user-attachments/assets/48abe4d6-54e9-48ad-9522-4ab169de1e46)

It seems to think that it is not a directory at all:

![Image](https://github.com/user-attachments/assets/46efb2b4-0a8c-4503-812a-654099af00eb)


But if I use the Databricks CLI I am able to list all of the contents of that metedata directory:

![Image](https://github.com/user-attachments/assets/0d8cbec5-d2a1-490a-b63f-03863af4b269)

Let me know if I can provide anything else here.

**Comment by henryryan17** [comment]
No, neither "path" nor "path/model" is listed. It is simply whatever folders, notebooks, files that I have in my local Workspace in my Adhoc folder.

**Comment by edgararuiz** [comment]
Yeah, I went ahead and revamped the entire way how `ml_load()` finds and reads the metadata. Before, it used the regular way R reads files to get the info from the metadata, and then it would read the pipeline via Spark. Now it will read the metadata and pipeline using the Spark Context

Would you mind trying the solution by installing the `updates` branch:

```r
devtools::install_github("sparklyr/sparklyr@updates")
suppressMessages(library(sparklyr)) 
sc <- spark_connect(method = "databricks")
ml_load(sc, "dbfs:/path/model")
```

**Comment by henryryan17** [comment]
@edgararuiz - That works! Everything looks great now

**Comment by edgararuiz** [comment]
Hi! Just a quick follow up. CRAN just accepted the new version of `sparklyr`, 1.9.1. This version contains the fix for this issue.
